
set AUTO_GEN_SCRIPT_PATH=%1
set AUTO_GEN_SCRIPT_GENERATOR=%2



call autogenerate.bat %AUTO_GEN_SCRIPT_PATH% %AUTO_GEN_SCRIPT_GENERATOR%
echo Executing autogenerated script ...
call %AUTO_GEN_SCRIPT_PATH%
del /q %AUTO_GEN_SCRIPT_PATH%


