rem @echo off



set AUTO_GEN_SCRIPT_PATH=%1
set AUTO_GEN_SCRIPT_GENERATOR=%2


set COMMAND_FOR_EXECUTE=%3
set FILE_TO_PROCESS_PATH=%4

call %AUTO_GEN_SCRIPT_GENERATOR%
 %AUTO_GEN_SCRIPT_PATH% %COMMAND_FOR_EXECUTE% %FILE_TO_PROCESS_PATH%


