@echo off

rem copy "C:\CMDEX\Interfaces\*.bat" "C:\CMDEX\Mirror\" 
rem call create_directory_if_not_exist.bat "C:\CMDEX\Mirror\Temp"

call create_directory_if_not_exist.bat "C:\CMDEX\Mirror"

echo Generating commands..
call ll "C:\CMDEX\Interfaces\*.bat" > "C:\CMDEX\Data\generate_mirror_temp.bat"
call sed -r -i "s/\.bat$//g" "C:\CMDEX\Data\generate_mirror_temp.bat"
call sed -r -i "s/^/echo\. \>\> C\:\\CMDEX\\Mirror\\/g" "C:\CMDEX\Data\generate_mirror_temp.bat"

echo Deleting old mirror..
del /q "C:\CMDEX\Mirror\*"

echo Executing autogenerated script..
call "C:\CMDEX\Data\generate_mirror_temp.bat"

del /q "C:\CMDEX\Data\generate_mirror_temp.bat"


